### ISSUE TITLE
我在登陆的时候,出现问题了找不到系统文件

### ISSUE THREAD

**Issue by markwhitey** [wxnacy/goss#1]
![190619185034742](https://user-images.githubusercontent.com/25740693/59759710-3d864b00-92c3-11e9-8009-1679f667fb42.png)

**Comment by wxnacy** [comment]
目前还么有适配windows系统，后续有时间我会加上

**Comment by markwhitey** [comment]
大佬,我还有一个问题哎,您是用的github page做的静态网页的话,图床分离有什么优点呢?

**Comment by wxnacy** [comment]
> 大佬,我还有一个问题哎,您是用的github page做的静态网页的话,图床分离有什么优点呢?

那是早期的时候，现在我没有用 github 做静态网页，用的 Nginx + Linux 来搞的，这样比较自由。图床分离也是为了迁移起来比较方便，我时不时会尝试新的博客框架。
